### ISSUE TITLE
Trying to test in background

### ISSUE THREAD

**Issue by ButuzGOL** [timfpark/react-native-location#13]
On simulator background works find but on device I puts console.logs but they not triggered
May you can help me ?

**Comment by ButuzGOL** [comment]
My code
console.log not triggered 
```
Location.requestAlwaysAuthorization();
Location.startUpdatingLocation();
Location.setDistanceFilter(5.0);

var subscription = DeviceEventEmitter.addListener(
    'locationUpdated',
    (location) => {
      console.log('updated');
    }
);
```

**Comment by timfpark** [comment]
Hi @ButuzGOL:  Are you using react-native v0.14 or greater?  I believe background JavaScript event support was added as of v0.14.

**Comment by ButuzGOL** [comment]
I am using ^0.18.0-rc

**Comment by gasperz** [comment]
For me it is also not working on real device. Testing with RN 0.21.0-rc1. But working on simulator.

**Comment by gasperz** [comment]
I have just discovered that another function is exposed in this implementation:
`Location.setAllowsBackgroundLocationUpdates(true);`
With adding this code, it is indeed working in background mode. But I think it was added only in iOs9 [(link)](https://developer.apple.com/library/ios/documentation/CoreLocation/Reference/CLLocationManager_Class/#//apple_ref/occ/instp/CLLocationManager/allowsBackgroundLocationUpdates)
So I guess also documentation (about setAllowsBackgroundLocationUpdates) should be update.

**Comment by ButuzGOL** [comment]
thanks I will try
