### ISSUE TITLE
Can you add the values of 'location' to the README?

### ISSUE THREAD

**Issue by pickhardt** [timfpark/react-native-location#2]
I'm looking at this right now and it's unclear what "location" returns. Can you add that to the README?

For example, is it 'latitude' and 'longitude'? Is there a city name? Is it this data? https://developer.apple.com/library/ios/documentation/CoreLocation/Reference/CLLocation_Class/

Specifically this part of the README could be improved:

```
var subscription = DeviceEventEmitter.addListener(
    'locationUpdated',
    (location) => {
        /**
          Location will be of the form:
          {'lat': ..., 'long': ..., etc}
    }
);
```

**Comment by timfpark** [comment]
I added this a few months ago...
