### ISSUE TITLE
Does it works with Android?

### ISSUE THREAD

**Issue by Partysun** [timfpark/react-native-location#21]

**Comment by caledhwa** [comment]
Right now this library is only suited for iOS as far as I know. There’s another library out there forked from this one that does support Android. 

Look at: https://github.com/agrass/react-native-gps

Good luck!

**Comment by EricPKerr** [comment]
@matt-oakes it would be awesome to support Google's FusedLocation API for Android if support for that platform gets added. Thanks!

**Comment by matt-oakes** [comment]
This feature was added in [v2.0.0 beta 1](https://github.com/timfpark/react-native-location/releases/tag/2.0.0-beta.1), however, the fallback to the built-in API is not complete yet.
