### ISSUE TITLE
What is the difference compared to Geolocation ?

### ISSUE THREAD

**Issue by note89** [timfpark/react-native-location#24]
Hi ! 
I'm intressted to know the benefits of this library compared to https://facebook.github.io/react-native/docs/geolocation.html

We are currently using that in our app, but its very slow on android compared to IOS. 

Tnx :)

**Comment by ButuzGOL** [comment]
+

**Comment by LeBlaaanc** [comment]
@note89 your question is kind of off topic because this library doesn't even support Android, however, I would take a look at https://github.com/airbnb/react-native-maps and how they implement tracking, it should provide the same or similar data.

**Comment by kasemyassine** [comment]
I want to add to his question is this library more accurate? or it's just the same because I want an accurate gps location functions!

**Comment by note89** [comment]
Well if we just talk about IOS then. 
What are the benefits ? :)

**Comment by skadavan** [comment]
Same question. How is this project different from : https://facebook.github.io/react-native/docs/geolocation.html ?
Is it better in accuracy or power consumption?
