### ISSUE TITLE
Please add support for react native 0.4x

### ISSUE THREAD

**Issue by u0x01** [timfpark/react-native-location#28]
This repo can't working on react native 0.4x currently.

**Comment by pbassut** [comment]
+1

**Comment by tomtom92** [comment]
+1

**Comment by j8seangel** [comment]
It was fixed here https://github.com/timfpark/react-native-location/pull/26 so it is working now using the `master`branch

**Comment by digitaldavenyc** [comment]
@j8seangel I don't believe this was actually fixed because I just pulled on a fresh install and have quite a few `RCTBridge.h` errors.

**Comment by rogerluo410** [comment]
@digitaldavenyc  

replace `#import <React/RCTBridge.h>` instead of `#import "RCTBridge.h"` in project. 

I can build successful, but throw out 'undefined is not an Object (evaluating DeviceEventEmitter.addListener)'...  

My React-native version is 0.42.3

**Comment by matt-oakes** [comment]
Tracking in #35
