### ISSUE TITLE
Limit Update Frequency for Heading?

### ISSUE THREAD

**Issue by armenr** [timfpark/react-native-location#34]
Is there some way to limit the frequency (number of seconds) for how often heading gets updated? 

Thank you!

**Comment by misterXavier** [comment]
The same problem here... I'm waiting and waiting...

**Comment by armenr** [comment]
@misterXavier  -  I'm working on a fork with a fix. Stand by. :)

**Comment by matt-oakes** [comment]
This feature was added in [v2.0.0 beta 1](https://github.com/timfpark/react-native-location/releases/tag/2.0.0-beta.1).
