### ISSUE TITLE
Support for iOS 11

### ISSUE THREAD

**Issue by rexlow** [timfpark/react-native-location#38]
Will this library be updated to support iOS 11?

Running in iOS 11 currently and apparently no location data is recorded.

```
react-native: 0.44.0
react-native-location: 0.27.0
```

**Comment by christopherdro** [comment]
Double check your Xcode logs. You'll need to add new values to your Info.plist which are specific to iOS 11.  See https://github.com/transistorsoft/react-native-background-geolocation/issues/282#issuecomment-332282755
