### ISSUE TITLE
Native module cannot be null

### ISSUE THREAD

**Issue by karanpratapsingh** [timfpark/react-native-location#44]
Thanks for this library, it works good with android but with iOS it gives Native Module cannot be null error.

Things I did:

1. Installed the lib.
2. linked using react-native link
3. even linked location.coreframework lib

can someone help?

**Comment by matt-oakes** [comment]
Hi @karanpratapsingh,

Can you confirm that you rebuilt the app after linking everything? Just refreshing the javascript will not be enough.

If you did, can you confirm that you are linking the correct Xcode target (if you have multiple of them) and that there are no warnings being produced about missing libraries when you build the app?

Thanks,
Matt

**Comment by karanpratapsingh** [comment]
I followed the docs and rebuilt everything, great library, unfortunately
I’ve switched to navigator api as of now

**Comment by matt-oakes** [comment]
Ok. Thanks for the report @karanpratapsingh. I'll confirm myself if this is working later and close this issue if it looks like it is. It sounds like something was "off" with the linking, however, if you've moved to another library then that's fine 👍

**Comment by karanpratapsingh** [comment]
No problem bro, I’ll try it with a fresh project

**Comment by anniewey** [comment]
@karanpratapsingh Restart packager and rerun your project will solve the issue

**Comment by ankitjainOfficial** [comment]
@matt-oakes I had run into same problem. I unlinked the lib and tested, everything worked fine. Linked it back again, and the same error. Any suggestions, on what can be tried.

@karanpratapsingh Could you resolve the issue?

**Comment by karanpratapsingh** [comment]
@ankitjainOfficial , I haven't tried this library since feb, as I switched to using navigator.getLocationAsync() that comes with react native and works good enough for simple stuff,

**Comment by robertvorthman** [comment]
I fixed this issue by running ```pod install``` from the ios folder
