### ISSUE TITLE
subscribeToLocationUpdates can't get result

### ISSUE THREAD

**Issue by jiaxiucai** [timfpark/react-native-location#49]
RNLocation.configure({
      distanceFilter: 5.0
 })

 RNLocation.requestPermission({
      ios: "whenInUse",
      android: {
        detail: "coarse"
      }
    }).then(granted => {
      if (granted) {
        console.log("granted")
        this.locationSubscription = RNLocation.subscribeToLocationUpdates(locations => {
          console.log("获取位置",locations)
        /* Example location returned
        {
          speed: -1,
          longitude: -0.1337,
          latitude: 51.50998,
          accuracy: 5,
          heading: -1,
          altitude: 0,
          altitudeAccuracy: -1
          floor: 0
          timestamp: 1446007304457.029
        }
        */
        })
        console.log("granted1")
      }
    })

RNLocation.subscribeToLocationUpdates can't get locations?

**Comment by matt-oakes** [comment]
Hi. Thanks for the report. Can you provide more details about the issue you are facing. For example:

* What platforms are you seeing issues on?
* For iOS, what do you have for the privacy messages in your `Info.plist`?
* For Android, what permissions do you include in your `AndroidManifest.xml`?
* What is the exact error or problem you are facing?

I will close this issue until a bit more detail is provided.
