### ISSUE TITLE
iOS: How to request location permission again?

### ISSUE THREAD

**Issue by sinhpn92** [timfpark/react-native-location#53]
On iOS, after Don't allow permission. I cannot request permission again. How can i do it?

**Comment by matt-oakes** [comment]
This is a feature of iOS to stop app developer spamming users until they accept the permissions. You need to check if the status is "denied" before answer, and instead show a message telling the user they need to go to the app settings and manually enable it. You can link to that screen by calling this code:

```javascript
Linking.openURL("app-settings:");
```
