### ISSUE TITLE
subscribeToLocationUpdates  gets no value in android,I can't get the value, please help me

### ISSUE THREAD

**Issue by zhaochu0821** [timfpark/react-native-location#60]
![9D5DAE57BBA6B80CA54B99FC920DCD39](https://user-images.githubusercontent.com/27795580/56843835-03a75280-68d9-11e9-8853-e29d208692a9.jpg)
![369C8A6B7BBF469566D4EEB37E09565F](https://user-images.githubusercontent.com/27795580/56843849-2e91a680-68d9-11e9-9367-c13131dd48bf.jpg)
![3441967099A6573F4324B4C1868283C5](https://user-images.githubusercontent.com/27795580/56843850-3d785900-68d9-11e9-9185-0bd4e180e0cb.jpg)
![17B47F109CC4D8331C922BC41EB95FE8](https://user-images.githubusercontent.com/27795580/56843860-6b5d9d80-68d9-11e9-8862-9ad28fbc6c9e.jpg)

**Comment by zhaochu0821** [comment]
@matt-oakes

**Comment by matt-oakes** [comment]
Hello 👋 Thanks for submitting this issue. To help us triage your issue, can you please resubmit this issue using the templates provided.

**Comment by hieuplasma** [comment]
I'm facing this problem right now, did you have solution for this? Help me pls!
