### ISSUE TITLE
What is the unit of speed? (m/s  or km/h) What does course exactly mean in return value?

### ISSUE THREAD

**Issue by risingtalent22** [timfpark/react-native-location#62]

**Comment by matt-oakes** [comment]
Information on the speed (it's m/s):

* iOS: https://developer.apple.com/documentation/corelocation/cllocation/1423798-speed?language=objc
* Android: https://developer.android.com/reference/android/location/Location.html#getSpeed()

Course is the direction the phone is facing with `0` being north. Details are:

* iOS: https://developer.apple.com/documentation/corelocation/cllocation/1423832-course?language=objc
* Android: https://developer.android.com/reference/android/location/Location.html#getBearing()
