### ISSUE TITLE
Not Work background in Android

### ISSUE THREAD

**Issue by eazueta85** [timfpark/react-native-location#68]
I do not work in background on Android I leave the App in the background stop sending the location even if I have locked the device, in iOS everything works ok.
My configure:
"react-native": "0.57.8"

 RNLocation.configure({
      distanceFilter: 5.0, // Meters
      desiredAccuracy: {
        ios: "best",
        android: "highAccuracy"
      },
      // Android only
      androidProvider: "auto",
      interval: 5000, // Milliseconds
      fastestInterval: 10000, // Milliseconds
      maxWaitTime: 5000, // Milliseconds
      // iOS Only
      activityType: "other",
      allowsBackgroundLocationUpdates: true,
      headingFilter: 1, // Degrees
      headingOrientation: "portrait",
      pausesLocationUpdatesAutomatically: false,
      showsBackgroundLocationIndicator: false,
    })
RNLocation.requestPermission({
      ios: "always",
      android: {
        detail: "fine",
        rationale: {
          title: "Can we access your location?",
          message: "Lokate would like to use your location to show you people within a 50 ft distance , that are on the same places as you and if the match is done you can start being friends and chatting. Enter your device settings and change the button of the apps location to allways allow. Close and restart the app again.",
          buttonPositive: "OK",
          buttonNegative: "Cancel"
        }
      }
    })

**Comment by matt-oakes** [comment]
Sorry, there is not enough information here to give you any meaningful help. Please reply with more details about exactly what is wrong, the steps to reproduce it, and what you expect to happen.
