### ISSUE TITLE
Your Simple example not working in android

### ISSUE THREAD

**Issue by roysG** [timfpark/react-native-location#69]
import RNLocation from 'react-native-location';

RNLocation.configure({
  distanceFilter: 5.0
})

RNLocation.requestPermission({
  ios: "whenInUse",
  android: {
    detail: "coarse"
  }
}).then(granted => {
    if (granted) {
      this.locationSubscription = RNLocation.subscribeToLocationUpdates(locations => {
console.log('locations',locations);
        /* Example location returned
        {
          speed: -1,
          longitude: -0.1337,
          latitude: 51.50998,
          accuracy: 5,
          heading: -1,
          altitude: 0,
          altitudeAccuracy: -1
          floor: 0
          timestamp: 1446007304457.029
        }
        */
      })
    }
  })

The command line "console.log('locations',locations);",  called just once when init it.
When i tried to change location i do not get the new location.

Ios - working perfectly
Tested on latest version.

**Comment by matt-oakes** [comment]
Your issue is that you are asking for "coarse" permissions, so Android will only give you a broad area and not update it very often. If you change this to "fine" you should get more updates.
