### ISSUE TITLE
Could not find a `2.3.0` tag / release

### ISSUE THREAD

**Issue by xiankunatpushpay** [timfpark/react-native-location#73]
I've seen `2.3.0` has been released on `NPM`, but couldn't find it anywhere in this repo.
Would be nice to have a tag/release here to see changes we've made.

Thanks ❤️

**Comment by matt-oakes** [comment]
Thanks for letting me know. Sorry about that. I pushed, but it must have failed. I'm travelling at the minute and sometimes the internet is pretty bad.

Should be there now.
