### ISSUE TITLE
Does it use fused locations ?

### ISSUE THREAD

**Issue by viv3kk** [timfpark/react-native-location#75]
Does it use fused locations ?
> Fused Location Provider API
The fused location provider is a location API in Google Play services that intelligently combines different signals to provide the location information that your app needs.

**Comment by pentolbakso** [comment]
Yes,

https://github.com/timfpark/react-native-location/blob/master/android/src/main/java/com/github/reactnativecommunity/location/RNPlayServicesLocationProvider.java#L50
