### ISSUE TITLE
Background worker in Android

### ISSUE THREAD

**Issue by amirmatin** [timfpark/react-native-location#77]
I am having issue getting the app to return the location in background mode and I was wondering if it is even possible via this library ?
I am currently on Android. if it is possible is there any example / Documentation on it ?

I am on RN:  0.5.10
RN-cli : 2.0.1
Android 8 (Oreo)

Thanks

**Comment by matt-oakes** [comment]
This library should work in the background with the correct conformation, however, this library might be a better fit if you need always on background location (most apps don't):

https://github.com/transistorsoft/react-native-background-geolocation
