### ISSUE TITLE
Is there a way to access the heading of motion?

### ISSUE THREAD

**Issue by hossam-nasr** [timfpark/react-native-location#83]
I switched to using this library from the `@react-native-community/react-native-geolocation` because it uses Google Play Services for Android to get the user location, which is fantastic. It's worked great for me so far, but the one issue I'm having is I can't seem to be able to access the `heading` field anymore? I don't mean the heading of the phone itself (the "Bearing" in Android), but the `heading` of the direction of motion, similar to `Geolocation`. 

The objects I'm getting have the following structure:

```
{
   accuracy: 5,
   altitude: 0,
   altitudeAccuracy: -1,
   course: 264.38,
   floor: 0,
   latitude: 37.33232211,
   longitude: -122.05719234,
   speed: 33.56,
   timestamp: 1566321168401.32,
}
```

I'm getting a `course` field, but no `heading`. Is there any way I can get the `heading` as well? Thank you

**Comment by matt-oakes** [comment]
The `course` is the Android bearing. This is due to using the iOS terminology instead. The documentation for this is actually not correct and not explained very well.
