### ISSUE TITLE
type 503 warning

### ISSUE THREAD

**Issue by sainbayarus** [timfpark/react-native-location#84]
what does meaning "type 503 there is no valid location provider available". Some of devices with android os 9 cannot get location.   RequestPermission returns 'granted' but  when device's location  turned off, this message returns and can not get location.

**Comment by matt-oakes** [comment]
If the user has location services turned off, then there's no way for you to get their location. The library tells you this so you can handle it. If you really need to location, I recommend you tell the user why and tell them how to enable location services again.

**Comment by aymensmurf** [comment]
How can I get hold of that message {type: 503, message: 'there is no valid location provider available'} so that I can test it?

**Comment by shiftrtech** [comment]
There is a way to get this error on my app code, i did try using a `try - catch` but it doesnt works.

**Comment by Hard-Haad** [comment]
Is there any way to handle this error, I havnt found anything in the Read me

**Comment by paddy57** [comment]
Any update on  how to catch the error ?

**Comment by mehdinourollah** [comment]
Why did you close this issue when it's still not resolved ?! 

I am getting this warning despite of having try and catch ...Any help ?
