### ISSUE TITLE
pausesLocationUpdatesAutomatically in not working

### ISSUE THREAD

**Issue by roysG** [timfpark/react-native-location#85]
I put the app in the background and after 3 minutes the app move to suspend state.
Do i miss something?

react-native-location version: 2.2.1
react-native-cli: 1.0.0
react-native: 0.58.3

This is my configuration object:

 RNLocation.configure({
                    distanceFilter: 0, // Meters
                    desiredAccuracy: {
                        ios: "bestForNavigation",
                    },
                    activityType: "other",
                    allowsBackgroundLocationUpdates: true,
                    headingFilter: 1, // Degrees
                    headingOrientation: "portrait",
                    pausesLocationUpdatesAutomatically: false,
                    showsBackgroundLocationIndicator: false,
                });

                RNLocation.requestPermission({
                    ios: "always",
                }).then(granted => {
                    console.log('roy granted', granted);

                    if (granted) {
 this.unsubscribe = RNLocation.subscribeToLocationUpdates(async locations => {

                            const lastPosition = locations[0];
                            console.log('get location',lastPosition);
      })
}

      }

**Comment by matt-oakes** [comment]
This library is not really designed for background location updates, as most apps really don't need the users location that frequently. If you do, then I recommend using this library instead:

https://github.com/transistorsoft/react-native-background-geolocation
