### ISSUE TITLE
TypeError: undefined is not an object (near RNLocation.configure({..}).then(...)) 

### ISSUE THREAD

**Issue by naderabdalghani** [timfpark/react-native-location#96]
I have tried rebuilding but the error still persists on iOS. The package works flawlessly on Android though.

Error screenshot:
![Simulator Screen Shot - iPhone 6 - 2019-10-09 at 21 24 38](https://user-images.githubusercontent.com/33901325/66513368-3a65d380-eadb-11e9-9694-311411377ee9.png)

Code:
```
  handleGetDirections = () => {
    var directionsData;
    RNLocation.configure({
      distanceFilter: 5.0,
      allowsBackgroundLocationUpdates: true
    })
      .then(() =>
        RNLocation.requestPermission({
          ios: 'whenInUse',
          android: {
            detail: 'fine',
            rationale: {
              title: 'Location permission',
              message: 'Your location is essential to request help',
              buttonPositive: 'OK',
              buttonNegative: 'Cancel'
            }
          }
        })
      )...
```

**Comment by mileselectric** [comment]
I'm also getting this same issue.
Works fine on Android but not iOS

**Comment by shafikgomez** [comment]
I am getting the same error. Android Works perfect.

**Comment by gz2jbt** [comment]
I am experiencing the same error in iOS.  Followed directions and used code from the repo.  Please advise.

**Comment by naderabdalghani** [comment]
[react-native-geolocation-service](https://github.com/Agontuk/react-native-geolocation-service) is an alternative solution, which gave me no errors at all

**Comment by zachlendon** [comment]
We saw this also, I believe configure in https://github.com/timfpark/react-native-location/blob/d215c8c549330c677af9e30d6752768e6275e169/ios/RNLocation.m needs updated to return a promise.

**Comment by matt-oakes** [comment]
`configure` does not return a `Promise`. Just call it once before you use any other method in the library.

**Comment by zachlendon** [comment]
@matt-oakes Awesome! I’d propose updating https://github.com/timfpark/react-native-location/blob/9a1c5bf3f683c78de8e82b2820d284e543ef9ab0/example/App.js to reflect   this then.  The reader appears accurate.

**Comment by matt-oakes** [comment]
Done!
