### ISSUE TITLE
Not picking Exact Location.

### ISSUE THREAD

**Issue by prasanthyejje** [timfpark/react-native-location#97]
its is not at all returning the exact location not even the nearest also .

Versions: 
 "react-native": "0.60.5",
"react-native-location": "^2.5.0",

please can you help me to figure it. 

Thanks In Advance.

**Comment by MedFBoudis** [comment]
same here ; 

"react-native": "^0.58.6"
"react-native-location": "^2.2.0"

**Comment by ralvescosta** [comment]
Same here:

"react-native": "0.60.5",
"react-native-location": "^2.5.0",

**Comment by matt-oakes** [comment]
This is most likely because you have the wrong permissions on Android. You need to ask for "fine" permissions.
